# Generated by Django 5.2.8 on 2025-12-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_alter_categoria_descricao'),
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria'),
        ),
    ]
