# Generated by Django 5.2.8 on 2025-12-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descreva para que essa categoria será usada'),
        ),
    ]
